### PR TITLE
Add tel type to textfield to allow for phone number inputs

### PR DESCRIPTION
**Pull request by juliacochran**
Adding a new `TextField` type to support phone number entries. If we just use the `number` type today, entries such as 555-555-5555 are rejected.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 75445420a81cb0f80b271672c53e7a25387050cf

https://deploy-preview-239--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit fc585d159e20c389d97406924703989b84a8b5a2

https://deploy-preview-239--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a [changelog.md](https://github.com/pinterest/gestalt/blob/master/CHANGELOG.md) entry for your changes.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Bundle size increase
  </td>
    </tr>
  </tbody>
</table>



Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
--- | --- | --- | --- | --- | --- | --- |
gestalt.js | :small_red_triangle: 0.0% | :small_red_triangle: 0.0% | 264.89 KB | 264.9 KB | 59.11 KB | 59.12 KB
gestalt.es.js | :small_red_triangle: 0.0% | :small_red_triangle: 0.0% | 262.33 KB | 262.34 KB | 58.75 KB | 58.75 KB
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by chrislloyd** [comment]
@juliacochran ping!

**Comment by juliacochran** [comment]
Don't have time to finish updating :/ Will come back to it another time.

**Pull request closed without merging**
