### PR TITLE
Add new onEnded prop for Video end event

### PR DESCRIPTION
**Pull request by pfarejowicz**
Adds a new event callback for the `onEnded` event so that clients can be notified of the video playback ending.

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit d245083abf6e3bf67041a05baa310dd2367b0d73

https://deploy-preview-207--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit a120622604a529a160acf102c361326fcf670b8a

https://deploy-preview-207--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 27fb2686def92ac2fa11cfc4134701fa9a4a0f1a

https://deploy-preview-207--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Bundle size increase
  </td>
    </tr>
  </tbody>
</table>



Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
--- | --- | --- | --- | --- | --- | --- |
gestalt.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.1% | 263.84 KB | 264.09 KB | 58.86 KB | 58.9 KB
gestalt.es.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.1% | 261.29 KB | 261.54 KB | 58.49 KB | 58.54 KB
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
