### PR TITLE
Docs visual design tweaks

### PR DESCRIPTION
**Pull request by ponori**
Minor adjustments to the UI to be a little lighter and more friendly to larger monitors.

### CODE REVIEW

**Comment by ponori** [comment]
This is currently still very much in progress. I may need some assists on a few areas.

**Comment by cintiapub** [comment]
@ponori; Wow! it looks so different even with light changes, but I liked it! It seems just like a white canvas, making space for future enhancements. <3

--> Three things: (thoughts)

**Search filed**: It feels a little bit off is the search field placed in the center. Typically it goes to the left side (as it was before). Could we move it to the left? Also, it doesn't seem vertically aligned to the middle of the header container. 

**Careers link**: "Interested in working with Gestalt? Check out our Careers page!" It is floating in the center and can easily get lost. It feels disconnected to me. Can we add a gray background (it can have less height) as it was before?  And maybe we can make it a footer and add the Pinterest logo (the one on the header). 

**Logo**: Since you are updating the page, could we replace the Pinterest logo with the Gestalt logo (the green one)? I changed the green logo on the logo file for better contrast, we could use the green version, so it still feels like the old Gestalt somehow. It could also be a bit bigger than the Pinterest logo. We could add the Pinterest logo to the footer, to the left of the Careers page link. 

These are my initial thoughts!

**Comment by ponori** [comment]
Thanks @cintiapub!

1. Yeah, the SearchField needs love. I will likely need an assist with this portion of the UI.
2. Let's play with this one - I agree with the center aligning. The left aligning felt a little odd as well when it was right next to the sidebar. I'll continue to play with this. I personally am not a huge fan of the light gray background, but totally open to re-introducing if that's a minority opinion.
3. I couldn't figure out how to add the Gestalt logo - I'll need help with that as well.

**Comment by cintiapub** [comment]
@ponori; Got it! It makes sense; thanks for making these changes.
Zendesk (https://garden.zendesk.com/) has a simple header (similar to ours) on its page that might serve as a reference (logo/search placement). Maybe looking at their code source sparkles some idea. (sorry if it doesn't make sense, trying to help)

**Comment by christianvuerings** [comment]
Overall I like the cleanup, couple of notes:

# 1) Consistent content width

The content for
https://deploy-preview-1788--gestalt.netlify.app/screen_sizes
Screen Shot 2021-11-24 at 4 16 26 PM
is wider than
https://deploy-preview-1788--gestalt.netlify.app/eslint_plugin
Screen Shot 2021-11-24 at 4 16 32 PM

# 2) Bug in search

To repro:
1. Click in the SearchField
2. Click outside the SearchField

image

# 3) Spacing on smaller screens

* No space between `Gestalt Design System` and the Search input
* No space above the icons

image
image

# 4) This site is powered by Netlify

`This site is powered by Netlify` is required if we want to keep using the Open Source plan for netlify: https://www.netlify.com/legal/open-source-policy

An alternative is to use a badge:

> Must feature a link to our service on your main page, or all internal pages. You have two options:
> * We have premade badges for your convenience, or
> * You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.

**Comment by ponori** [comment]
Thanks so much Christian! This is all really helpful! Definitely a lot of
work to still do in order to get this out the door. I had no idea regarding
the Netlify link - thank you!

**Pull request closed without merging**
