### PR TITLE
Docs: Reorganize sidebar

### PR DESCRIPTION
**Pull request by chrislloyd**
I really love the new sidebar! However, it's a bit confusing because the first thing that's presented is "Data Display" and "Avatar" which... seems like not the most important thing to introduce people to Gestalt with. This PR reorganizes the sidebar to roughly order things in the order of "frequently used".

### CODE REVIEW

**Comment by chrislloyd** [comment]
@ajmoo @ashleyseto hey how does this seem to ya'll? Does it affect naming anywhere else?

**Comment by ajmoo** [comment]
Doesn't affect me what order you display things in! Has anyone else provided feedback that the previous layout is confusing?

**Comment by chrislloyd** [comment]
@ajmoo no feedback, just figured it was weird to have "Avatar" in "Data Display" and have "Foundation" below the fold. @christianvuerings does this look good to you?

**Comment by ashleyseto** [comment]
Original document had "foundations" first then everything else under it in alphabetical order. I think that makes the most sense unless we want additional categories to make the navigation deeper.

**Comment by christianvuerings** [comment]
Follow up at #1051

**Pull request closed without merging**
