### PR TITLE
[Docs] Adds a class to the page for Algolia to properly index search content

### PR DESCRIPTION
**Pull request by chrislloyd**
I contacted Algolia to add their [free docsearch product](https://community.algolia.com/docsearch/) to Gestalt. Their support engineer said that it was difficult to know what to index because of Gestalt's classnames so if I could add this, we can get the site indexed. Once it's indexed, I'll look at adding a searchbar to the header.

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit a291cd6b2970eaf8d0cbb30889c3667809d5025a

https://deploy-preview-153--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a [changelog.md](https://github.com/pinterest/gestalt/blob/master/CHANGELOG.md) entry for your changes.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by christianvuerings** [comment]
@chrislloyd is the first of 2 PRs to add search? Might have been helpful to add some more information to the github description

**Comment by chrislloyd** [comment]
Done. Will be experimenting with what the search UI actually looks like once Algolia has indexed the site.

**Pull request merged**
