### PR TITLE
New icons from design

### PR DESCRIPTION
**Pull request by Warbring3r**
Angled pin, arrow up-right, eye, and a hand pointing

### CODE REVIEW

**Comment by Warbring3r** [comment]
https://github.com/pinterest/gestalt/issues/105

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 5df3c60bbab4c0acaf9a19632313bcaf6433ba0b

https://deploy-preview-106--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a [changelog.md](https://github.com/pinterest/gestalt/blob/master/CHANGELOG.md) entry for your changes.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Warbring3r** [comment]
These icons are from Justin Carson

**Comment by MateusGabi** [comment]
New Icons is not avaible on documentation (https://deploy-preview-106--gestalt.netlify.com/#/Icon). Is it right?

**Comment by pfarejowicz** [comment]
@Warbring3r you have to import it into index.js and export it there as well. I also noticed your change log comment should go in the unreleased section

**Comment by Warbring3r** [comment]
@pfarejowicz @MateusGabi addressed your comments. Will the icons automatically appear in the documentation deploy preview?

**Comment by pfarejowicz** [comment]
Yup, check out https://deploy-preview-106--gestalt.netlify.com/#/Icon you can see the new ones

**Comment by Warbring3r** [comment]
@chrislloyd Design just told me they have slightly updated the icons (the "eye" looks odd on mobile) so I am going to wait and update this PR once the updated icons are ready.

**Pull request merged**
