### PR TITLE
Link: Update docs to make href required and update children proptype

### PR DESCRIPTION
**Pull request by kennandavison**

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 004ecf92aa2ea5bb6cc308d26cc7e25e230d90f2

https://deploy-preview-380--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit ed4e8525b22659b161c7c289ead99de01bd74973

https://deploy-preview-380--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
gestalt.js | :small_red_triangle_down: 0.0% | :small_red_triangle: 0.0% | 300.59 KB | 300.58 KB | 61.77 KB | 61.77 KB
gestalt.es.js | :small_red_triangle_down: 0.0% | :small_red_triangle: 0.0% | 284.27 KB | 284.26 KB | 60.85 KB | 60.85 KB
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by chrislloyd** [comment]
Closing out. Feel free to re-open if still relevant.

**Pull request closed without merging**
