### PR TITLE
Callout: Added responsiveness design

### PR DESCRIPTION
**Pull request by AlbertCarreras**
### Figma Design
image

### Before

image

### After

image

### CODE REVIEW

**Comment by ashleyseto** [comment]
Assuming this is just for the responsiveness. Looking good! Only one small thing is on the smaller size we dropped the internal padding from 32px to 24px.

**Comment by AlbertCarreras** [comment]
@ashleyseto I checked the margins. Let me know if I'm missing something.
Kapture 2020-07-31 at 11 24 23

**Comment by christianvuerings** [comment]
@AlbertCarreras lgtm - not specific to your diff but one thing I really wish we had is something like https://github.com/marcj/css-element-queries . Instead of relying on the browser window sizes it relies on the element size

**Comment by ashleyseto** [comment]
I saw this was merged but the design hadn't been updated. I'm still seeing the content at 32px

Screen Shot 2020-07-31 at 4 38 37 PM

**Pull request merged**
