### PR TITLE
Layouts: Add form layout example

### PR DESCRIPTION
**Pull request by christianvuerings**
# Layouts

* Add a "Layouts" page
* Add a `Form Layout` example which is responsive, works with RTL and dark mode

layouts-form-layout

## Test Plan

- [ ] Test on netlify as soon as the preview goes out
- [ ] Approved by design /cc @ashleyseto @anniemochi

### CODE REVIEW

**Comment by ashleyseto** [comment]
I think it looks correct. I'm not sure about the implementation though. I would expect it to be 24px bottom rather than around. It is adding space to the left and the right that might not be wanted when trying to line up content inside containers like the Module that should already have padding defined.

**Comment by christianvuerings** [comment]
> I think it looks correct. I'm not sure about the implementation though. I would expect it to be 24px bottom rather than around. It is adding space to the left and the right that might not be wanted when trying to line up content inside containers like the Module that should already have padding defined.

@ashleyseto agreed - I removed the padding around so it will work within other containers which already have padding set. As to the bottom (and left/right) - we do use symmetrical padding in Gestalt since:
* It automatically looks good when the elements wrap one below the other
* Works with RTL
* There is no need to know whether the next row will be rendered which helps with composability of each row. (We see this use case quite often on the Pinterest settings page)

**Review by ashleyseto — APPROVED** [review]

**Comment by AlbertCarreras** [comment]
@christianvuerings https://www.loom.com/share/2a0615667601470b8cc39bb314e9b00a Not an expert on accessibility at all. Should the screen reader read the form title?.

**Comment by christianvuerings** [comment]
> @christianvuerings https://www.loom.com/share/2a0615667601470b8cc39bb314e9b00a Not an expert on accessibility at all. Should the screen reader read the form title?.

@AlbertCarreras Yes, that is correct and it does read it when you instruct the screenreader to do so.

See https://webaim.org/articles/voiceover/#reading for how to navigate with voiceover. When running through, I usually use
`VO` + `→`: `Read next item`
When you simply tab through, it will only focus on the elements that can have focus (e.g. TextField / Button)

screenreader-form-layouts

**Review by AlbertCarreras — APPROVED** [review]

**Pull request merged**
