### PR TITLE
Add new icons for text alignment

### PR DESCRIPTION
**Pull request by loserford**
New icons added:

```
text-align-center: packages/gestalt/src/icons/text-align-center.svg
text-align-left: packages/gestalt/src/icons/text-align-left.svg
text-align-right: packages/gestalt/src/icons/text-align-right.svg
```

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 9b27f5c0bc19f650352f87f2f510c18ba17506aa

https://deploy-preview-401--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :file_folder: Bundlesize - <i>Bundle size increase detected, please review</i>
  </td>
    </tr>
  </tbody>
</table>


Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
gestalt.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.2% | 300.6 KB | 300.99 KB | 61.77 KB | 61.88 KB
gestalt.es.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.2% | 284.27 KB | 284.65 KB | 60.85 KB | 60.98 KB
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by loserford** [comment]
@pfarejowicz yes, it was run by PDS (PD-627).

**Comment by pfarejowicz** [comment]
> @pfarejowicz yes, it was run by PDS (PD-627).

🙌 ship it!

**Pull request merged**
