### PR TITLE
Change event prop callbacks to mixed

### PR DESCRIPTION
**Pull request by kennandavison**
https://github.com/pinterest/gestalt/issues/354

Use Case:

Before (to have no flow errors):
```
async function apiCall() { await apiCall() }
<Button onClick={() => apiCall}>Make Async Call</a>
```

After:
```
async function apiCall() { await apiCall() }
<Button onClick={apiCall}>Make Async Call</a>
```

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 4dcd504bb59fac9c252097f6cce927fc74ee56c6

https://deploy-preview-360--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 0325b61665d3fbcd1bdcc16b805b5cd1c0f78659

https://deploy-preview-360--gestalt.netlify.com

**Comment by pfarejowicz** [comment]
do you mind typing up an example use case here of how you plan to use this new `mixed` return type inside a component?

**Comment by pfarejowicz** [comment]
@chrislloyd what do you think? i do see the `mixed` return type in the flow docs for arbitrary functions, but maybe an `|` is better here?

**Comment by chrislloyd** [comment]
Closing out. Feel free to re-open if still relevant.

**Pull request closed without merging**
