### PR TITLE
ActivationCard, Avatar, Badge, Callout, Checkbox, ComboBox, Datapoint, Dropdown, Heading, IconButton: add visual diff testing and screenshot to description in VSCode (Flow extension)

### PR DESCRIPTION
**Pull request by AlbertCarreras**
#### What changed?

ActivationCard, Avatar, Badge, Callout, Checkbox, ComboBox, Dropdown, Datapoint, Heading, IconButton: add visual diff testing and screenshot to description in VSCode (Flow extension)

#### Why?

Provide basic visual testing coverage for most Gestalt components and link screenshots to VSCode's Flow extension that shows component screenshot below the component description on hover for better in-editor documentation.

OKR: 
- Tooling & Infra
- Visual Diff testing 
- Every component in our library uses visual diff testing to guard against UI regression

### CODE REVIEW

**Review by dangerismycat — COMMENTED** [review]
This is awesome, thanks!!

It looks like something's up with Callout in dark mode. Is this expected?
Screen Shot 2022-02-23 at 3 25 55 PM

**Comment by AlbertCarreras** [comment]
> This is awesome, thanks!!
> 
> It looks like something's up with Callout in dark mode. Is this expected? Screen Shot 2022-02-23 at 3 25 55 PM
Screen Shot 2022-02-24 at 1 12 27 AM
Unfortunately yes.

**Comment by dangerismycat** [comment]
> > This is awesome, thanks!!
> > It looks like something's up with Callout in dark mode. Is this expected? Screen Shot 2022-02-23 at 3 25 55 PM
> 
> Screen Shot 2022-02-24 at 1 12 27 AM
> 
> Unfortunately yes.

Ah right. Should we include dark mode screenshots for components that don't yet support them? They're not actually useful for visual diff testing or for the VS Code extension.

**Comment by AlbertCarreras** [comment]
> > > This is awesome, thanks!!
> > > It looks like something's up with Callout in dark mode. Is this expected? Screen Shot 2022-02-23 at 3 25 55 PM
> > 
> > 
> > Screen Shot 2022-02-24 at 1 12 27 AM
> > Unfortunately yes.
> 
> Ah right. Should we include dark mode screenshots for components that don't yet support them? They're not actually useful for visual diff testing or for the VS Code extension.

Removed from Flow description, keeping dark mode as visual diff test.

**Comment by dangerismycat** [comment]
The point of visual diff snapshots is to capture the "correct" visual state of the component so we can catch future regressions. Capturing the incorrect state is useless at best, and will mean that future updates to support dark mode in that component will actually "break" the test, which is the opposite of what we want.

**Pull request merged**
