### PR TITLE
update gestalt version

### PR DESCRIPTION
**Pull request by akulkapoor**
Updating gestalt to 0.69.0

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit f252eaa4d13cc0be2ad3d96971bb79fcb90a7480

https://deploy-preview-172--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 8ab7c5547ac6b1bb5752b58cc10eb232afcb3c77

https://deploy-preview-172--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 5de25ca7dbf4784c2e4834803834e2d7ccdc071e

https://deploy-preview-172--gestalt.netlify.com

**Comment by chrislloyd** [comment]
Lets wait for #171 to land first

**Pull request merged**
