### PR TITLE
Tabs: Use href for key instead of index

### PR DESCRIPTION
**Pull request by kennandavison**
https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 8c18a2f7dabb53a8991b6c8adc85ef6a0cb99d7d

https://deploy-preview-368--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 609b0b0d3a6fe1b472b1e5b4f6e39bb0710f061d

https://deploy-preview-368--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 54b8688eac8a715b52869e33ba9b52109ffa8464

https://deploy-preview-368--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :file_folder: Bundlesize - <i>Bundle size increase detected, please review</i>
  </td>
    </tr>
  </tbody>
</table>


Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
gestalt.js | :small_red_triangle: 0.0% | :small_red_triangle: 0.0% | 300.59 KB | 300.61 KB | 61.77 KB | 61.78 KB
gestalt.es.js | :small_red_triangle: 0.0% | :small_red_triangle: 0.0% | 284.27 KB | 284.28 KB | 60.85 KB | 60.86 KB
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
