### PR TITLE
Callout: Include Node type for Message property

### PR DESCRIPTION
**Pull request by simkessy**
Using a React Node in the message causes a type error: 

image

### CODE REVIEW

**Comment by ashleyseto** [comment]
@simkessy 
We do not wish to change the message area to react node. Bold is our link style so these may be confused as links. I'd recommend removing the bold right now in that message and updating the design.

**Comment by AlbertCarreras** [comment]
Hey Kessy, can we close this PR until the design for this is discussed?

**Comment by simkessy** [comment]
> @simkessy
> We do not wish to change the message area to react node. Bold is our link style so these may be confused as links. I'd recommend removing the bold right now in that message and updating the design.

@ashleyseto  I need a react node to get the spacing / separation between the lines. A string alone won't allow us to do that.

**Comment by ashleyseto** [comment]
> > @simkessy
> > We do not wish to change the message area to react node. Bold is our link style so these may be confused as links. I'd recommend removing the bold right now in that message and updating the design.
> 
> @ashleyseto I need a react node to get the spacing / separation between the lines. A string won't allow us to do that.

Hey, I would encourage you to ask your designer to sign up for design system office hours then. We should first start with the design and make a decision. The PR should come after design approval not the other way around. @anniemochi for the creators side of things.

Ideally we do not open this up to "node" that is too much freedom for this component. It may not be the right pattern here.

**Pull request closed without merging**
