### PR TITLE
Add new animation to Pulsar

### PR DESCRIPTION
**Pull request by kathrynwu**
Testing out an optional pulsar animation on web:
https://codepen.io/shanawho/pen/LmZoOP?editors=1100

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 3c7831214929b005602c7536dc7ef38200a5858a

https://deploy-preview-272--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :memo: CHANGELOG - <i>Please add a CHANGELOG.md entry for your changes</i>
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :file_folder: Bundlesize - <i>Bundle size increase detected, please review</i>
  </td>
    </tr>
  </tbody>
</table>


Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
gestalt.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.1% | 254.56 KB | 254.8 KB | 56.73 KB | 56.78 KB
gestalt.css | :small_red_triangle: 1.8% | :small_red_triangle: 0.9% | 53.05 KB | 53.99 KB | 9.08 KB | 9.16 KB
gestalt.es.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.1% | 251.93 KB | 252.17 KB | 56.35 KB | 56.4 KB
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by christianvuerings** [comment]
@kathrynwu Would it be possible to do this experimentation in the Pinterest codebase? For instance, create an `ExperimentalPulsar` component and swap it out depending on the treatment group?

In gestalt itself we try to avoid having props that are experimental.

**Comment by kathrynwu** [comment]
@christianvuerings  Copy that

**Comment by christianvuerings** [comment]
@kathrynwu Closing this for now.
Feel free to re-open with the new animation if the experiment was successful.

**Pull request closed without merging**
