### PR TITLE
Link: fix duplicate css declaration

### PR DESCRIPTION
**Pull request by volny**
text-decoration is already composed from Typography.css

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 6e4cb049dbe6a5f93b83d62259fe54e086f60ee0

https://deploy-preview-118--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a [changelog.md](https://github.com/pinterest/gestalt/blob/master/CHANGELOG.md) entry for your changes.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by christianvuerings** [comment]
@volny Thank you for spotting that an fixing it! Would you be able to also add your change to `CHANGELOG.md`?

**Comment by volny** [comment]
@christianvuerings done, `CHANGELOG.md` updated. Hope I did this right, if not please let me know.

**Comment by christianvuerings** [comment]
@volny looks great! Thanks again.

**Pull request merged**
