### PR TITLE
Icon: Add download svg

### PR DESCRIPTION
**Pull request by kennandavison**

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit db0960d35bf920dd2f60e20b9a62d1c1a8f32102

https://deploy-preview-341--gestalt.netlify.com

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit cfe6752f367b0b7af4068b5971011a18b7c62518

https://deploy-preview-341--gestalt.netlify.com

**Comment by christianvuerings** [comment]
@kennandavison definitely needs an optimization:

image

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :file_folder: Bundlesize - <i>Bundle size increase detected, please review</i>
  </td>
    </tr>
  </tbody>
</table>


Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
gestalt.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.2% | 274.11 KB | 274.37 KB | 59.36 KB | 59.48 KB
gestalt.es.js | :small_red_triangle: 0.1% | :small_red_triangle: 0.2% | 259.26 KB | 259.52 KB | 58.47 KB | 58.58 KB
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
