### PR TITLE
Update README.md (Added Typescript Support)

### PR DESCRIPTION
**Pull request by serranoarevalo**

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit e1572e8b3184571c430310a1dbe330d90f19b547

https://deploy-preview-300--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :memo: CHANGELOG - <i>Please add a CHANGELOG.md entry for your changes</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by serranoarevalo** [comment]
@pfarejowicz No problem! Can we get this merged?

**Comment by pfarejowicz** [comment]
merged @serranoarevalo, thanks again!

**Pull request merged**
